# Site settings
title: Codemancy.io
email: valentin@thedotin.ro
description: > # this means to ignore newlines until "baseurl:"
  Hello, I'm Naveen, a freelance front-end developer
  and UI designer. Check out my projects on GitHub
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://codemancy.io" # the base hostname & protocol for your site

css: "purple"
scroll-cursor: "#00BCD4"
scroll-rail: "#0097A7"

# Build settings
markdown: kramdown
highlighter: null #pygments
lsi: false
safe: false

# theme: jekyll-theme-minimal